general:
buildTool: "mta"

stages:
  Build:
   mavenExecuteStaticCodeChecks:
   npmExecuteLint: true 

  Additional Unit Tests:
   npmExecuteScripts: false
   karmaExecuteTests: false

  Acceptance:
   cloudFoundryDeploy: false
   cfApiEndpoint: "https://api.cf.us10-001.hana.ondemand.com"
   cfOrg: "060a0275trial"
   cfSpace: "dev"
   cfAppName: "app"
   cfCredentialsId: "deploy-to-cf"
   uiVeri5ExecuteTests: false